
import java.awt.Color;
import javax.swing.JOptionPane;

public class tictactoe extends javax.swing.JFrame {
private String A="x";
private String playerone="player three";
private String playertwo="player two";
private int playeronecount=0;
private int playertwocount=0;
    
    public tictactoe() {
        initComponents();
        setSize(600, 600);
        setLocationRelativeTo(null);
        playername();
        score();
    }
    private void losing(){
     String one=jButton1.getText();
    String two=jButton2.getText();
    String three=jButton3.getText();
    String four=jButton4.getText();
    String five=jButton5.getText();
    String six=jButton6.getText();
    String seven=jButton7.getText();
    String eight=jButton8.getText();
    String nine=jButton9.getText();
       if(one !=""&&two !=""&&three !=""&&four !=""&&five !=""&&six !=""&&seven !=""&&eight !=""&&nine !=""){
           JOptionPane.showMessageDialog(null, "game is unefficient q" ,"not result",JOptionPane.INFORMATION_MESSAGE);
           resetgame();
       }
    }
    
    private void score(){
        jLabel1_score.setText(playerone+"  score is   :"+  String.valueOf(playeronecount) +"        "+ playertwo+"   score  is  :"+ String.valueOf(playertwocount));
        
    }

    private void playername(){
playerone=JOptionPane.showInputDialog(null, "player one name","players name",JOptionPane.INFORMATION_MESSAGE);
playertwo=JOptionPane.showInputDialog(null, "player two name","players name",JOptionPane.INFORMATION_MESSAGE);
     if(playerone.equals("")){
         playerone="player one";
     }
         if(playertwo.equals("")){
             playertwo="player two";
         }
        
    }
    private void B()
    {
        if(A.equalsIgnoreCase("x"))
        {
            A="o";
        }
        else{
            A="x";
        }
    }
    
    private void xwiner(){
        JOptionPane.showMessageDialog(null, playerone+" winer","anjam",JOptionPane.INFORMATION_MESSAGE);
        playeronecount++;    
        resetgame();
                 
    }
    private void owiner(){
         JOptionPane.showMessageDialog(null, playertwo+" winer","anjam",JOptionPane.INFORMATION_MESSAGE); 
           playertwocount++;
         resetgame();
      
    }
    private void resetgame(){
        jButton1.setText("");
        jButton2.setText("");
        jButton3.setText("");
        jButton4.setText("");
        jButton5.setText("");
        jButton6.setText("");
        jButton7.setText("");
        jButton8.setText("");
        jButton9.setText("");
        score();
    }
    private void xoif(){
    
    String one=jButton1.getText();
    String two=jButton2.getText();
    String three=jButton3.getText();
    String four=jButton4.getText();
    String five=jButton5.getText();
    String six=jButton6.getText();
    String seven=jButton7.getText();
    String eight=jButton8.getText();
    String nine=jButton9.getText();
    
    if(one=="x"&&two=="x"&&three=="x"){
        xwiner();
    }
    if(four=="x"&&five=="x"&&six=="x"){
        xwiner();
    }
    if(seven=="x"&&eight=="x"&&nine=="x"){
        xwiner();
    }
    if(one=="x"&&four=="x"&&seven=="x"){
        xwiner();
    }
    if(two=="x"&&five=="x"&&eight=="x"){
        xwiner();
    }
    if(three=="x"&&six=="x"&&nine=="x"){
        xwiner();
    }
    if(one=="x"&&five=="x"&&nine=="x"){
        xwiner();
    }
    if(three=="x"&&five=="x"&&seven=="x"){
        xwiner();
    }
        
      
    if(one=="o"&&two=="o"&&three=="o"){
      owiner();
    }
    if(four=="o"&&five=="o"&&six=="o"){
        owiner();
    }
    if(seven=="o"&&eight=="o"&&nine=="o"){
        owiner();
    }
    if(one=="o"&&four=="o"&&seven=="o"){
        owiner();
    }
    if(two=="o"&&five=="o"&&eight=="o"){
        owiner();
    }
    if(three=="o"&&six=="o"&&nine=="o"){
        owiner();
    }
    if(one=="o"&&five=="o"&&nine=="o"){
      owiner();
    }
    if(three=="o"&&five=="o"&&seven=="o"){
     owiner();
    }
        
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1_score = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        xanay1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        xanay2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        xanay3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        xanay4 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        xanay5 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        xanay6 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        xanay7 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        xanay8 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        xanay9 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("tictactoe");
        setBackground(new java.awt.Color(102, 102, 102));

        jLabel1_score.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1_score.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1_score.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1_score.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1_score.setText("place holder");
        getContentPane().add(jLabel1_score, java.awt.BorderLayout.PAGE_END);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new java.awt.GridLayout(3, 3, 1, 1));

        xanay1.setBackground(new java.awt.Color(255, 255, 255));
        xanay1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        xanay1.setLayout(new java.awt.BorderLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        xanay1.add(jButton1, java.awt.BorderLayout.CENTER);

        jPanel1.add(xanay1);

        xanay2.setBackground(new java.awt.Color(255, 255, 255));
        xanay2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        xanay2.setLayout(new java.awt.BorderLayout());

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        xanay2.add(jButton2, java.awt.BorderLayout.CENTER);

        jPanel1.add(xanay2);

        xanay3.setBackground(new java.awt.Color(255, 255, 255));
        xanay3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        xanay3.setLayout(new java.awt.BorderLayout());

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        xanay3.add(jButton3, java.awt.BorderLayout.CENTER);

        jPanel1.add(xanay3);

        xanay4.setBackground(new java.awt.Color(255, 255, 255));
        xanay4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        xanay4.setLayout(new java.awt.BorderLayout());

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        xanay4.add(jButton4, java.awt.BorderLayout.CENTER);

        jPanel1.add(xanay4);

        xanay5.setBackground(new java.awt.Color(255, 255, 255));
        xanay5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        xanay5.setLayout(new java.awt.BorderLayout());

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        xanay5.add(jButton5, java.awt.BorderLayout.CENTER);

        jPanel1.add(xanay5);

        xanay6.setBackground(new java.awt.Color(255, 255, 255));
        xanay6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        xanay6.setLayout(new java.awt.BorderLayout());

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        xanay6.add(jButton6, java.awt.BorderLayout.CENTER);

        jPanel1.add(xanay6);

        xanay7.setBackground(new java.awt.Color(255, 255, 255));
        xanay7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        xanay7.setLayout(new java.awt.BorderLayout());

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        xanay7.add(jButton7, java.awt.BorderLayout.CENTER);

        jPanel1.add(xanay7);

        xanay8.setBackground(new java.awt.Color(255, 255, 255));
        xanay8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        xanay8.setLayout(new java.awt.BorderLayout());

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        xanay8.add(jButton8, java.awt.BorderLayout.CENTER);

        jPanel1.add(xanay8);

        xanay9.setBackground(new java.awt.Color(255, 255, 255));
        xanay9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        xanay9.setLayout(new java.awt.BorderLayout());

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        xanay9.add(jButton9, java.awt.BorderLayout.CENTER);

        jPanel1.add(xanay9);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     jButton1.setText(A);
     if(A.equalsIgnoreCase("X"))
     {
         jButton1.setForeground(Color. green);
     }
     else{
           jButton1.setForeground(Color.yellow);
         
     }
     B();
     xoif();
     losing();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          jButton2.setText(A);
            if(A.equalsIgnoreCase("X"))
     {
         jButton2.setForeground(Color.red);
     }
     else{
           jButton2.setForeground(Color.blue);
         
     }
     B();
      xoif();
       losing();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jButton3.setText(A);
          if(A.equalsIgnoreCase("X"))
     {
         jButton3.setForeground(Color.red);
     }
     else{
           jButton3.setForeground(Color.blue);
         
     }
     B();
      xoif();
       losing();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         jButton4.setText(A);
           if(A.equalsIgnoreCase("X"))
     {
         jButton4.setForeground(Color.red);
     }
     else{
           jButton4.setForeground(Color.blue);
         
     }
     B();
      xoif();
       losing();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
           jButton5.setText(A);
             if(A.equalsIgnoreCase("X"))
     {
         jButton5.setForeground(Color.red);
     }
     else{
           jButton5.setForeground(Color.blue);
         
     }
     B();
      xoif();
       losing();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jButton6.setText(A);
          if(A.equalsIgnoreCase("X"))
     {
         jButton6.setForeground(Color.red);
     }
     else{
           jButton6.setForeground(Color.blue);
         
     }
     B();
      xoif();
       losing();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
   jButton7.setText(A);
     if(A.equalsIgnoreCase("X"))
     {
         jButton7.setForeground(Color.red);
     }
     else{
           jButton7.setForeground(Color.blue);
         
     }
     B();
      xoif();
       losing();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
         jButton8.setText(A);
           if(A.equalsIgnoreCase("X"))
     {
         jButton8.setForeground(Color.red);
     }
     else{
           jButton8.setForeground(Color.blue);
         
     }
     B();
      xoif();
       losing();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
         jButton9.setText(A);
           if(A.equalsIgnoreCase("X"))
     {
         jButton9.setForeground(Color.red);
     }
     else{
           jButton9.setForeground(Color.blue);
         
     }
     B();
      xoif();
       losing();
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tictactoe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tictactoe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tictactoe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tictactoe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tictactoe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1_score;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel xanay1;
    private javax.swing.JPanel xanay2;
    private javax.swing.JPanel xanay3;
    private javax.swing.JPanel xanay4;
    private javax.swing.JPanel xanay5;
    private javax.swing.JPanel xanay6;
    private javax.swing.JPanel xanay7;
    private javax.swing.JPanel xanay8;
    private javax.swing.JPanel xanay9;
    // End of variables declaration//GEN-END:variables
}
